// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: attribute.proto

package position_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AttributeServiceClient is the client API for AttributeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AttributeServiceClient interface {
	CreateAttribute(ctx context.Context, in *CreateAttributeRequest, opts ...grpc.CallOption) (*Attribute, error)
	GetAllAttribute(ctx context.Context, in *GetAllAttributeRequest, opts ...grpc.CallOption) (*GetAllAttributeResponse, error)
	GetByIdAttribute(ctx context.Context, in *AttributeId, opts ...grpc.CallOption) (*Attribute, error)
	UpdateAttribute(ctx context.Context, in *Attribute, opts ...grpc.CallOption) (*Attribute, error)
	DeleteAttribute(ctx context.Context, in *AttributeId, opts ...grpc.CallOption) (*AttributeId, error)
}

type attributeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAttributeServiceClient(cc grpc.ClientConnInterface) AttributeServiceClient {
	return &attributeServiceClient{cc}
}

func (c *attributeServiceClient) CreateAttribute(ctx context.Context, in *CreateAttributeRequest, opts ...grpc.CallOption) (*Attribute, error) {
	out := new(Attribute)
	err := c.cc.Invoke(ctx, "/position_service.AttributeService/CreateAttribute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeServiceClient) GetAllAttribute(ctx context.Context, in *GetAllAttributeRequest, opts ...grpc.CallOption) (*GetAllAttributeResponse, error) {
	out := new(GetAllAttributeResponse)
	err := c.cc.Invoke(ctx, "/position_service.AttributeService/GetAllAttribute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeServiceClient) GetByIdAttribute(ctx context.Context, in *AttributeId, opts ...grpc.CallOption) (*Attribute, error) {
	out := new(Attribute)
	err := c.cc.Invoke(ctx, "/position_service.AttributeService/GetByIdAttribute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeServiceClient) UpdateAttribute(ctx context.Context, in *Attribute, opts ...grpc.CallOption) (*Attribute, error) {
	out := new(Attribute)
	err := c.cc.Invoke(ctx, "/position_service.AttributeService/UpdateAttribute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attributeServiceClient) DeleteAttribute(ctx context.Context, in *AttributeId, opts ...grpc.CallOption) (*AttributeId, error) {
	out := new(AttributeId)
	err := c.cc.Invoke(ctx, "/position_service.AttributeService/DeleteAttribute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttributeServiceServer is the server API for AttributeService service.
// All implementations must embed UnimplementedAttributeServiceServer
// for forward compatibility
type AttributeServiceServer interface {
	CreateAttribute(context.Context, *CreateAttributeRequest) (*Attribute, error)
	GetAllAttribute(context.Context, *GetAllAttributeRequest) (*GetAllAttributeResponse, error)
	GetByIdAttribute(context.Context, *AttributeId) (*Attribute, error)
	UpdateAttribute(context.Context, *Attribute) (*Attribute, error)
	DeleteAttribute(context.Context, *AttributeId) (*AttributeId, error)
	mustEmbedUnimplementedAttributeServiceServer()
}

// UnimplementedAttributeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAttributeServiceServer struct {
}

func (UnimplementedAttributeServiceServer) CreateAttribute(context.Context, *CreateAttributeRequest) (*Attribute, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAttribute not implemented")
}
func (UnimplementedAttributeServiceServer) GetAllAttribute(context.Context, *GetAllAttributeRequest) (*GetAllAttributeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllAttribute not implemented")
}
func (UnimplementedAttributeServiceServer) GetByIdAttribute(context.Context, *AttributeId) (*Attribute, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByIdAttribute not implemented")
}
func (UnimplementedAttributeServiceServer) UpdateAttribute(context.Context, *Attribute) (*Attribute, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAttribute not implemented")
}
func (UnimplementedAttributeServiceServer) DeleteAttribute(context.Context, *AttributeId) (*AttributeId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAttribute not implemented")
}
func (UnimplementedAttributeServiceServer) mustEmbedUnimplementedAttributeServiceServer() {}

// UnsafeAttributeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttributeServiceServer will
// result in compilation errors.
type UnsafeAttributeServiceServer interface {
	mustEmbedUnimplementedAttributeServiceServer()
}

func RegisterAttributeServiceServer(s grpc.ServiceRegistrar, srv AttributeServiceServer) {
	s.RegisterService(&AttributeService_ServiceDesc, srv)
}

func _AttributeService_CreateAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeServiceServer).CreateAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/position_service.AttributeService/CreateAttribute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeServiceServer).CreateAttribute(ctx, req.(*CreateAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeService_GetAllAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeServiceServer).GetAllAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/position_service.AttributeService/GetAllAttribute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeServiceServer).GetAllAttribute(ctx, req.(*GetAllAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeService_GetByIdAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttributeId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeServiceServer).GetByIdAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/position_service.AttributeService/GetByIdAttribute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeServiceServer).GetByIdAttribute(ctx, req.(*AttributeId))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeService_UpdateAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Attribute)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeServiceServer).UpdateAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/position_service.AttributeService/UpdateAttribute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeServiceServer).UpdateAttribute(ctx, req.(*Attribute))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttributeService_DeleteAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttributeId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeServiceServer).DeleteAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/position_service.AttributeService/DeleteAttribute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeServiceServer).DeleteAttribute(ctx, req.(*AttributeId))
	}
	return interceptor(ctx, in, info, handler)
}

// AttributeService_ServiceDesc is the grpc.ServiceDesc for AttributeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttributeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "position_service.AttributeService",
	HandlerType: (*AttributeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAttribute",
			Handler:    _AttributeService_CreateAttribute_Handler,
		},
		{
			MethodName: "GetAllAttribute",
			Handler:    _AttributeService_GetAllAttribute_Handler,
		},
		{
			MethodName: "GetByIdAttribute",
			Handler:    _AttributeService_GetByIdAttribute_Handler,
		},
		{
			MethodName: "UpdateAttribute",
			Handler:    _AttributeService_UpdateAttribute_Handler,
		},
		{
			MethodName: "DeleteAttribute",
			Handler:    _AttributeService_DeleteAttribute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "attribute.proto",
}
